version: '3.4'

services:
  mysql:
    image: mysql:8
    volumes:
     - ./docker/mysql/sql-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=PimpMyBDD
      - MYSQL_ROOT_PASSWORD=P1mpMy@pp5
      - MYSQL_USER=pimmy
      - MYSQL_PASSWORD=pimmy
    # healthcheck:
    #   test: ["CMD", "pg_isready"]
    #   interval: 15s
    #   timeout: 5s
    #   retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=P1mpMy@pp5
    ports:
      - 8080:80
